server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  mvc:
  servlet:
    multipart:
      max-file-size: 10MB        # 设置单个文件最大大小为10MB
      max-request-size: 100MB    # 设置多个文件大小为100MB
  datasource:
    type: ${selfstudy.datasource.type}
    driver-class-name: ${selfstudy.datasource.driver-class-name}
    url: jdbc:mysql://${selfstudy.datasource.host}:${selfstudy.datasource.port}/${selfstudy.datasource.database}?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${selfstudy.datasource.username}
    password: ${selfstudy.datasource.password}


mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ytd.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      ytd:
        mapper: debug
        service: info
        controller: info

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


selfstudy:
   jwt:
     # 设置jwt签名加密时使用的秘钥
     admin-secret-key: ytd
     # 设置jwt过期时间
     admin-ttl: 7200000
     # 设置前端传递过来的令牌名称
     admin-token-name: token


github:
  bucket:
      user: ${selfstudy.github.bucket.user}
      repository: ${selfstudy.github.bucket.repository}
      access-token: ${selfstudy.github.bucket.access-token}
      url: ${selfstudy.github.bucket.url}
      api: ${selfstudy.github.bucket.api}