selfstudy:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: self_study
    username: root
    password: yangtongde

  github:
    bucket:
      user: KagariWorld
      repository: selfstudy_images
      access-token: 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
      url: https://cdn.jsdelivr.net/gh/${github.bucket.user}/${github.bucket.repository}/
      api: https://api.github.com/repos/${github.bucket.user}/${github.bucket.repository}/contents/